### ISSUE TITLE
insert footer 

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#103]
- [x] We can ask if we can use this page information for our footer.  https://digitale-lehre.virtuos.uni-osnabrueck.de/impressum/
- [x] create an impressum page and insert the information from the DigiLehre Portal 
- [x] remove crossed out items
- [x] link walk-in hours: https://digitale-lehre.virtuos.uni-osnabrueck.de/?event=virtuos-offene-online-sprechstunde-5

![image](https://github.com/yesidc/toolbox/assets/110525911/36a6ba36-8aed-483b-9cea-6d7d20654bc3)

**Comment by yesidc** [comment]
@LyLutter is there a link to `Ideenpool (DE)`?

**Comment by yesidc** [comment]
@LyLutter What about having a link to the GitHub repo in `Team` ?

**Comment by LyLutter** [comment]
Good idea, yes, let's put a Link to the Git Hub repo. 
 
This is the link to Ideenpool https://digitale-lehre.virtuos.uni-osnabrueck.de/Ideenpool/Ideenpool_Praxistipps_Komplett.pdf

**Comment by LyLutter** [comment]
Link to Ideenpool flash cards: https://digitale-lehre.virtuos.uni-osnabrueck.de/Ideenpool/Ideenpool_Praxistipps_Komplett.pdf

**Comment by LyLutter** [comment]
Please check rows and columns of the footer.
