### ISSUE TITLE
Redesign the style of the checklist page warning: you have not selected any idea from the building blocks... 

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#16]
design/ style less disruptive

**Comment by yesidc** [comment]
This is how it looks currently, do you have any suggestions?  
![Screen Shot 2022-09-21 at 2 37 23 PM](https://user-images.githubusercontent.com/46203884/191505475-bbada5d4-5299-4333-8246-b8d6937c7237.png)

**Comment by LyLutter** [comment]
Download starts in the same tab. --> change it to be opened in another tab. 

Change message to: 
"You have not selected any teaching tools for building block"
