### ISSUE TITLE
Change property terms on preview page and detail page

### ISSUE THREAD

**Issue by SabrinaFrohn** [yesidc/toolbox#21]
- [x] "online idea" --> Teaching tool 
 - [x]  "examples of application" --> "Use cases" 
 - [x] "Tool" --> "Technology"

**Comment by LyLutter** [comment]
- [ ] "online idea" --> Teaching tool 
 - [ ]  "examples of application" --> "Use cases" 
 - [ ] "Tool" --> "Technology"

**Comment by yesidc** [comment]
done!
