### ISSUE TITLE
Links to a page in the tool box

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#33]
I don't know how to link to pages within the tool box (Checkboxes). Below a list of instances which are incomplete because of that. 
Assessment > Assignment checklist
- [x] Syllabus 

Discussion> Practice as you preach
- [x] Syllabus
- [ ] Course emails 

Human Touch >Anecdotes & Stories 
- [x] link to micro lectures page

**Comment by yesidc** [comment]
@LyLutter I couldn't find an idea called 'Course emails'

**Comment by yesidc** [comment]
solved using this js function `open_internal_link`
