### ISSUE TITLE
Add picture to BB human Touch json file

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#37]
Add this picture in the accordion
![Riemann-Thomann Modell](https://user-images.githubusercontent.com/110525911/199965208-663ae859-5cd5-4c5e-86de-3169d41c7520.png)

**Comment by yesidc** [comment]
To add images (change accordingly): `<img src="/static/tbcore/images/my_image.png" alt="" width="40%" height="50%" class="rounded mx-auto d-block">`
