### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#43]
1. picture as a banner (suggestion below, draft version to be polished) 
2. Put text below the arm
3. Can we use less space for the banner so that the next section of the landing page is already piquing? 
4. remove space

![image](https://user-images.githubusercontent.com/110525911/200597579-2ec14641-0e90-4cc1-81e9-74531490c5ae.png)
![technology-ga78ffae86_1920](https://user-images.githubusercontent.com/110525911/200598705-16e753b9-73e6-4f57-a99a-d293c5977920.JPG)

**Comment by yesidc** [comment]
@LyLutter is there a final version of the picture that I can already use? or shall I use this one (above)?
