### ISSUE TITLE
Building block page

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#44]
# Building block page
remove current course on the right hand side 
![image](https://user-images.githubusercontent.com/110525911/200326511-def95742-55f2-41a0-b391-74906283e06d.png)

## Accordion not on full width and centered? 

![image](https://user-images.githubusercontent.com/110525911/200325634-9638b649-d672-4cd9-b0ea-cb545e150d12.png)

## Cards: 
![image](https://user-images.githubusercontent.com/110525911/200347360-cde65c93-e2c0-49dd-a8c1-86fc7a69f8a6.png)

1. - add shadow, 
   - slight coloring, I like the rainbow effect
    - round corners
    - same size as on twillo website (80x80)
![image](https://user-images.githubusercontent.com/110525911/200326751-94e72bcd-4fcd-41ea-badb-e12e514d4f24.png)
2. no icons 
3. no brief description

_Originally posted by @LyLutter in https://github.com/yesidc/toolbox/issues/8#issuecomment-1305644458_

**Comment by yesidc** [comment]
we can user this tool to choose the card's background color [](https://mycolor.space/gradient?ori=to+left+top&hex=%23051237&hex2=%23EBC512&sub=1)

**Comment by LyLutter** [comment]
background-image: radial-gradient(circle, #032671, #8a2279, #d73660, #f97936, #ebc512);
