### ISSUE TITLE
Landing page text and buttons

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#48]
1. "Start course revision" (we don't have to tell them that they have to log in because they will be redirected to log in anyways) Make
2. "Browse without log-in"
3. change to bullet point list. 

- Find teaching tools and technology to open your courses for online learning
- Assess the effort
- Create your personal checklist with notes and ideas on the teaching tools you select (sign in) 

![image](https://user-images.githubusercontent.com/110525911/200819258-9dc2c950-2938-4008-90cc-3aab16efdb5e.png)

**Comment by LyLutter** [comment]
1. Here comes a picture of the building blocks of a house 
2. "This tool box walks you through 8 building blocks of a sound online course. Per building block, different teaching tools and technologies are suggested to meet the minimum requirements for online courses. The details of each teaching tool help you to estimate the effort you have to make, and you can take notes which will be saved to a personalized checklist which you can use for course preparation."
![image](https://user-images.githubusercontent.com/110525911/200853795-4e3b3eb3-69e4-490d-8c10-8e1d90bf3d7d.png)

**Comment by LyLutter** [comment]
"Further general teaching tips, news and updates about technology supported by VirtUOS are published on the Digitale Lehre Portal. Additionally, all (topic-related) walk-in hours and meetings about trending topics from the didactical colloquium "Lehrkolleg" are announced there."

![image](https://user-images.githubusercontent.com/110525911/200856129-2ba1b0af-01c4-4182-92e9-50617811b861.png)

**Comment by LyLutter** [comment]
## Landing page after Log-in
1. Remove "Do you want to work on an existing course?" and keep only the button instead, that should suffice. 
2. same button type 
3. Move "Keep working on existing courses" button next to the "save" button
4. Change "save" --> "start" 
![image](https://user-images.githubusercontent.com/110525911/200857435-5424620e-7716-495a-8d46-900ded4df78e.png)

**Comment by yesidc** [comment]
Pending: add the picture. @LyLutter Does the image already exist?
