### ISSUE TITLE
Messages and warnings 

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#49]
Change to "Your course plan was deleted" 
![image](https://user-images.githubusercontent.com/110525911/200857926-702218e9-e11a-4278-9063-25487a502de0.png)

**Comment by LyLutter** [comment]
The warning is in german for me, is it english for you?

**Comment by LyLutter** [comment]
"Teaching tool successfully added to your course plan."

**Comment by LyLutter** [comment]
Change to "My Course Plans"
![image](https://user-images.githubusercontent.com/110525911/200861623-55ab55ac-89ac-4339-9e50-d4e8dd016cc1.png)

**Comment by yesidc** [comment]
Pending: add/delete message.
