### ISSUE TITLE
Remove detail_view to eliminate a third level 

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#7]
Instead of the third level, we could integrate the details of the teaching methods in an accordeon fashion. (Sabria suggested this when the preview page showed all details and was not a preview showing only 1-2 senteces/ 3 lines max. We should ask other users whatthe prefer.

**Comment by yesidc** [comment]
@LyLutter, Shall I close this issue? I think we already decided to have a third level, right?
