### ISSUE TITLE
Improve footer 

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#74]
come up with a design 
- include all necessary information there

**Comment by LyLutter** [comment]
Info about what needs/ can be included 
https://www.ionos.de/digitalguide/websites/webseiten-erstellen/was-ist-ein-footer/

**Comment by LyLutter** [comment]
[virtuos@uos.de](mailto:virtuos@uos.de)

**Comment by LyLutter** [comment]
Tobias: Can we link to this page? https://digitale-lehre.virtuos.uni-osnabrueck.de/impressum/

**Comment by yesidc** [comment]
@LyLutter is there a Figma design/sketch I can already use?

**Comment by LyLutter** [comment]
https://www.figma.com/file/OzdDvR31pXausuy4z8Z7na/Landing-page-Toolbox?type=design&node-id=0%3A1&t=q3PA8EcTDDzvsd41-1
