### ISSUE TITLE
Edit messages

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#84]

**Comment by LyLutter** [comment]
![image](https://github.com/yesidc/toolbox/assets/110525911/6ee2381a-6a60-432e-9628-b155b7715e49)

**Comment by LyLutter** [comment]
edit browser message when leaving the note without save

**Comment by LyLutter** [comment]
- [ ] Remove "Hint:"  

![image](https://github.com/yesidc/toolbox/assets/110525911/3a41950d-c79c-4fbe-af98-3af7642b01fa)

**Comment by LyLutter** [comment]
I clicked on delete and then did not confirm. My plan was deleted, which is a bug, I suppose. 
After logging in again, my plan is back. Is this the default course plan? If yes, we should get rid of message 1. 


![image](https://github.com/yesidc/toolbox/assets/110525911/1381ed99-4b4b-42ed-b860-0b9253524635)

**Comment by LyLutter** [comment]
![image](https://github.com/yesidc/toolbox/assets/110525911/d9279d83-f39b-4847-b818-fe6bc2aa6cba)

**Comment by LyLutter** [comment]
![image](https://github.com/yesidc/toolbox/assets/110525911/80f47544-c3de-47f3-8c13-a434ff36147b)

**Comment by yesidc** [comment]
by `box color shade of red: H = 0 S =83 B = 69 T = 40% (or 20%, let's check)` you mean --> `rgb(215,55,55);opacity: 0.4`

**Comment by LyLutter** [comment]
No, the RGB code for the red color is (176, 30, 30) 20%, I don't know the opacity. 
With sqaured buttons I meant to ask if we can put a button there saying "login" instead of a link saying "login".
