### ISSUE TITLE
edit welcome message 

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#85]
"Welcome back user! We have automatically loaded rules and regulations cour plan for you to continue working on it." 
Welcome
tell users which course plan has been loaded for them.

**Comment by yesidc** [comment]
What do you mean? `rules and regulations` is the name of the course plan

**Comment by LyLutter** [comment]
- [ ] Change message idea added to my plan
![image](https://github.com/yesidc/toolbox/assets/110525911/3f5b49b5-b55d-46a2-b2db-00064a98c382)

**Comment by LyLutter** [comment]
- [ ]  1. Can we get rid of the pink <p> highlighted in pink? 
- [ ] 2. Can we make it a clickable link? 
- [ ] 3. Please change the text 
![image](https://github.com/yesidc/toolbox/assets/110525911/988f1d65-fadf-4510-8f7b-d7f900eb45ec)
