### ISSUE TITLE
Own files stored in database

### ISSUE THREAD

**Issue by LyLutter** [yesidc/toolbox#93]
- Where are the files stored? 
- How can we update them? 
- How do I link them in the Json files? 
 <a href="**/static/tbcore/support_documents/**How_to_add_task_plugIn_to_Stud.Ip_course.pdf" target="_blank">Tasks (reflection) Plug-In</a>

**Comment by LyLutter** [comment]
@yesidc Please add instructions to read me. Thank you!

**Comment by yesidc** [comment]
Information can be found under the ``About the json5 files/Static files (json5)``.
